name: Run Tests with Pytest and Generate Allure Report

on:
  push:
    branches:
      - main  # Запуск при пуше в main
  pull_request:
    branches:
      - main  # Запуск при пулл-реквестах в main

jobs:
  test:
    runs-on: ubuntu-latest  # Операционная система для выполнения действий

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  #

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run tests with pytest
      run: |
        pytest --maxfail=10

    - name: Install allure commandline
      run: |
        sudo apt-get update
        sudo apt-get install -y allure  

    - name: Generate Allure report
      run: |
        allure generate ./allure_results --clean -o ./allure_report  
        allure open ./allure_report  

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: ./allure_report