name: Run tests with Allure report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Install Allure Commandline
        run: |
          sudo apt-get update -y
          sudo apt-get install -y allure
          allure --version

      - name: Run tests and generate Allure report
        run: |
          python run.py

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure_report

      - name: Start Allure server
        run: |
          allure open allure_report