name: Run Tests with Pytest and Generate Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --alluredir=./allure_results

    - name: Install Allure commandline
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
        tar -zxvf allure-2.18.1.tgz
        sudo mv allure-2.18.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Generate Allure report
      run: |
        allure generate ./allure_results --clean -o ./allure_report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure_report

    - name: Clean up Allure artifacts
      run: |
        rm -rf allure-2.18.1.tgz allure-2.18.1