name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Используем Windows вместо Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Устанавливаем Allure через Chocolatey на Windows
    - name: Install Allure commandline
      run: |
        choco install allure-commandline

    # Запуск тестов
    - name: Run Tests
      run: |
        pytest tests/ --alluredir=allure_results

    # Генерация отчета Allure
    - name: Generate Allure Report
      run: |
        allure generate ./allure_results -o ./allure_report --clean

    # Открытие отчета Allure (необязательно)
    - name: Open Allure Report
      run: |
        allure open ./allure_report