name: Run Tests with Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонировать репозиторий
    - name: Checkout code
      uses: actions/checkout@v2

    # Шаг 2: Установить зависимости для Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Шаг 3: Установить Allure и необходимые зависимости
    - name: Install Allure
      run: |
        sudo apt-get update -y
        sudo apt-get install -y allure
        sudo ln -sf /opt/allure-commandline-2.17.0/bin/allure /usr/local/bin/allure

    # Шаг 4: Установить зависимости Python
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Шаг 5: Запуск автотестов через run.py
    - name: Run tests
      run: |
        python run.py

    # Шаг 6: Генерация отчета Allure
    - name: Generate Allure report
      run: |
        allure generate --clean

    # Шаг 7: Публикация Allure отчета как артефакта
    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    # Шаг 8: Проверка версии Allure
    - name: Verify Allure version
      run: allure --version