name: Run Auto Tests

on:
  push:
    branches:
      - master  # Запускать при пуше в main
  pull_request:
    branches:
      - master  # Запускать при пулл-реквестах в main

jobs:
  test:
    runs-on: ubuntu-latest  # Операционная система для выполнения действий

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Клонируем репозиторий

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Указываем версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Install Allure Commandline
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.17.0/allure-2.17.0.zip -O allure.zip
        unzip allure.zip -d /opt
        sudo ln -s /opt/allure-2.17.0/bin/allure /usr/local/bin/allure  

    - name: Set up .env variables
      run: |
        echo "RUN=test_smoke.py::TestSmoke" >> .env  
        echo "MARKER=smoke" >> .env  

    - name: Run tests
      run: |
        python run.py
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.12.8/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.8/x64/lib
        RUN: test_smoke.py::TestSmoke  # Указываем переменную RUN
        MARKER: smoke  # Указываем переменную MARKER

    - name: Generate Allure Report
      run: |
        allure generate -c ./allure_results -o ./allure_report
        allure open ./allure_report