name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # или любая другая ветка, в зависимости от того, где вы хотите запускать CI
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Проверка вашего кода

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Укажите вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
        pip install python-dotenv  
        pip install allure-pytest  

    - name: Run tests
      env:
        RUN: "*"
        MAXFAIL: "10"
        MARKER: "smoke"
      run: |
        python run.py  

    - name: Generate allure report
      run: |
        allure generate ./allure_results -o ./allure_report --clean

    - name: Upload Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure_report