name: Run Tests with Pytest and Generate Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Шаг 4: Запуск автотестов с использованием pytest
    - name: Run tests with pytest
      run: |
        pytest --maxfail=10 --alluredir=./allure_results

    # Шаг 5: Установка Allure commandline
    - name: Install Allure commandline
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
        tar -zxvf allure-2.18.1.tgz
        sudo mv allure-2.18.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    # Шаг 6: Генерация Allure отчета
    - name: Generate Allure report
      run: |
        allure generate ./allure_results --clean -o ./allure_report

    # Шаг 7: Загрузка Allure отчета как артефакта
    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure_report

    # Шаг 8: Очистка временных файлов Allure
    - name: Clean up Allure artifacts
      run: |
        rm -rf allure-2.18.1.tgz allure-2.18.1